Address Travis error by using full class name, not self::
In PHP 5.3, there was:
Fatal error: Cannot access self:: when no class scope is active.
https://travis-ci.org/Automattic/amp-wp/jobs/386045157.

This looks to be because self isn't
available inside the function in 5.3.
Another option might be to add $self to use().
But this seems simpler, if it works.